### PR TITLE
add bindings to most of the FLINT library

### PR DESCRIPTION
**Pull request by wjyoumans**
Most of the FLINT library is included but all of the bindings need tests and documentation (the docs in the original bindings are omitted as I recreated the bindings from scratch since some were missing).

### CODE REVIEW

**Comment by wjyoumans** [comment]
I also removed the `gmp-mpfr-sys` dependency since it downloads and compiles gmp and mpfr from source and isn't necessary unless we want access to gmp and mpfr functions. The equivalent gmp and mpfr types are defined in `deps.rs`.

**Comment by alex-ozdemir** [comment]
Finally got some time to look at this. Two comments, one question.

Comment: I'd like to keep some test around that checks for interoperability with GMP. I've pushed a commit that switches `gmp_mpfr_sys` to a dev dependency, and copied in the old interop test.

Question: did you do this by hand, or use some kind of generator? If the latter, it would be good to check in the generator, to enable future changes.

Comment: this is really great! I'm very happy to have more thorough bindings. Thank you!

**Comment by wjyoumans** [comment]
No problem!

I understand having GMP tests. Making it a dev dependency is a good idea!

It was a mix of both which is why I didn't add any generating script. The bindings were generated with [bindgen](https://github.com/rust-lang/rust-bindgen) and I cleaned them up as much as I could by hand since it seemed like the fastest option (I'm still not sure if that was the right call...). However, I definitely dislike not having a generating script since it means any FLINT changes may be difficult to accommodate :/ 

I could add the crate for generating the raw bindings for now if you want, but it will need a decent amount of work before it can produce something like these.

**Comment by alex-ozdemir** [comment]
> I could add the crate for generating the raw bindings for now if you want

Yeah, this would be great. I don't think we need to block on having a full generator.

**Comment by alex-ozdemir** [comment]
Pinging @wyoumansUSF: do you have the time/interest to add a script for running bidgen? If not, no worries: I'm happy to merge this as-is.

**Comment by wjyoumans** [comment]
Sorry about the delay! Yes I will add the bindgen stuff. I should have a chance this week.

**Comment by wjyoumans** [comment]
The bindgen script is included now in the flint-bindgen crate.

**Comment by wjyoumans** [comment]
@alex-ozdemir any feedback on this PR? I'm working on making the binding generation as close to 100% automatic as I can while I work on bindings for a couple other libraries as well as update these bindings to FLINT 2.8.

**Comment by wjyoumans** [comment]
Merging master into this PR corrupted git objects/refs. Rather than try to patch it up I've moved the PR onto a new branch with corrected refs.

**Pull request closed without merging**
